[package]
name = "bc_indicators_gw"
version = "0.1.0"
edition = "2024"

[dependencies]
bc_indicators ={ git = "https://github.com/rXZD5cFumBJnx56wcclz/bc_indicators.git", branch = "main"}
bc_utils_lg ={ git = "https://github.com/rXZD5cFumBJnx56wcclz/bc_utils_lg.git", branch = "main"}
bc_utils = {git = "https://github.com/rXZD5cFumBJnx56wcclz/bc_utils.git", branch = "main"}

[dev-dependencies]
bc_test_kit = {git = "https://github.com/rXZD5cFumBJnx56wcclz/bc_test_kit.git", branch = "main"}
bc_packs = {git = "https://github.com/rXZD5cFumBJnx56wcclz/bc_packs.git", branch = "main"}

criterion = {version = "0.3.5", features = ["html_reports"]}
pretty_assertions = "1"

[[bench]]
name = "gw"
harness = false
path = "benches/gw.rs"
